### ISSUE TITLE
no anything？

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [PolyTimotheos/MinistryOfFlat-BlenderAddon#1]
what？

**Comment by PolyTimotheos** [comment]
Hey there ! 
I have a really simple version up and running which we're using at my company.
I always planned to extend it with the ability to actually be able to configure the settings as well, but never got around to have the time to actually do that. I always thought someone would probably created a better version of this by now? 
Would this even be useful to you in its current state ?

**Comment by PolyTimotheos** [comment]
Ok i've uploaded the addon and added a small readme which does provide the most important information about the addon
